services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .git
    restart: always
    ports:
      - "8080:8080"
